### ISSUE TITLE
Recherche collaborateurs pour les différents modules

### ISSUE THREAD

**Issue by pimarin** [mesocentre-clermont-auvergne/formation_fair_2022#14]
- Demander à des bioinfos sensibilisés aux principes FAIR de participer ?
    - Nadia --> mésocentre
    - Pauline --> INRA GDEC
    - Hélène --> INRA GDEC
    - Pierre --> mésocentre
    -  Matteo --> git ?

**Comment by nagoue** [comment]
done with Mateo (git), 
Philippe (INRAE MEDIS) encapsulation and documentation
me for snakemake
